# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6143b7cf870c42c1120e1ebcba5c64d6ce2168e54844f44eacbe58994a9342f4c6cadcedffafadfe34496d1eebb37b47726a6878de0c254e870086497022510b

test:
  secret_key_base: acb960e8f8931ad6baffd6995c246a00b9b4cd9e8becbf96125ef6e0a7df5070348f5f9140fead116c8d22b6b6fd0acea7db480694cb8d124933df5a1a3b194e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
